version: '3'

services:
  client-backend:
    container_name: meteo-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8003
      - SPRING.DATASOURCE.URL=jdbc:postgresql://service-db/meteo

  service-db:
    image: bitnami/postgresql:14
    container_name: meteo-db
    env_file:
      - ./src/main/resources/application.properties
    ports:
      - "5444:5444"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aobubu" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    external:
      name: agronetwork

volumes:
  pgdbdata: