"""Init

Revision ID: 08511d7a3065
Revises: 
Create Date: 2024-11-11 23:03:04.770465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08511d7a3065'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('parse_meteo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meteo_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('soil_temperature_0cm', sa.Float(), nullable=True),
    sa.Column('soil_temperature_6cm', sa.Float(), nullable=True),
    sa.Column('soil_temperature_18cm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_0_to_1cm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_1_to_3cm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_3_to_9cm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_9_to_27cm', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('precipitation_sum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meteo_data_field_id'), 'meteo_data', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meteo_data_field_id'), table_name='meteo_data')
    op.drop_table('meteo_data')
    op.drop_table('fields')
    # ### end Alembic commands ###
